import type { OsiModel } from './osi-types'

export const defaultModel: OsiModel = {
  info: {
    name: 'sales_semantic_model',
    version: '1.0.0',
    description: '销售域语义模型：统一定义订单、客户相关的维度与指标口径',
    owner: 'data-platform@example.com',
    domain: 'sales',
    defaultTimezone: 'Asia/Shanghai',
    locale: 'zh-CN',
    certified: true,
    tags: ['sales', 'core', 'certified'],
  },
  datasets: [
    {
      id: 'ds_orders',
      name: 'orders',
      label: '订单',
      description: '订单事实表',
      database: 'analytics',
      schema: 'dwd',
      table: 'fact_orders',
      sql: '',
      dimensions: [
        {
          id: 'dim_order_id',
          name: 'order_id',
          label: '订单号',
          expr: 'order_id',
          dataType: 'string',
          description: '订单唯一标识',
          synonyms: ['订单号'],
          sampleValues: ['ORD-2026-000123'],
          isTimeDimension: false,
          isPrimaryKey: true,
          isUnique: true,
          classification: 'internal',
        },
        {
          id: 'dim_order_date',
          name: 'order_date',
          label: '下单日期',
          expr: 'order_created_at',
          dataType: 'timestamp',
          description: '订单创建时间',
          synonyms: ['下单时间', '成交日期'],
          sampleValues: [],
          isTimeDimension: true,
          granularity: 'day',
          isPrimaryKey: false,
          isUnique: false,
          classification: 'internal',
        },
        {
          id: 'dim_region',
          name: 'region',
          label: '销售大区',
          expr: 'sales_region',
          dataType: 'string',
          description: '销售大区',
          synonyms: ['大区', '区域'],
          sampleValues: ['华东', '华南', '华北'],
          isTimeDimension: false,
          isPrimaryKey: false,
          isUnique: false,
          classification: 'public',
        },
      ],
      facts: [
        {
          id: 'fact_amount',
          name: 'order_amount',
          label: '订单金额',
          expr: 'order_amount',
          dataType: 'decimal',
          description: '订单成交金额（不含税）',
          synonyms: ['金额', '成交额'],
        },
        {
          id: 'fact_quantity',
          name: 'item_quantity',
          label: '商品数量',
          expr: 'item_quantity',
          dataType: 'integer',
          description: '订单包含的商品件数',
          synonyms: ['件数'],
        },
      ],
    },
    {
      id: 'ds_customers',
      name: 'customers',
      label: '客户',
      description: '客户维度表',
      database: 'analytics',
      schema: 'dim',
      table: 'dim_customers',
      sql: '',
      dimensions: [
        {
          id: 'dim_customer_id',
          name: 'customer_id',
          label: '客户ID',
          expr: 'customer_id',
          dataType: 'string',
          description: '客户唯一标识',
          synonyms: ['客户ID'],
          sampleValues: [],
          isTimeDimension: false,
          isPrimaryKey: true,
          isUnique: true,
          classification: 'confidential',
        },
        {
          id: 'dim_segment',
          name: 'segment',
          label: '客户分层',
          expr: 'customer_segment',
          dataType: 'string',
          description: '客户分层',
          synonyms: ['客群', '分层'],
          sampleValues: ['KA', 'SMB', 'Enterprise'],
          isTimeDimension: false,
          isPrimaryKey: false,
          isUnique: false,
          classification: 'internal',
        },
      ],
      facts: [],
    },
  ],
  metrics: [
    {
      id: 'm_revenue',
      name: 'total_revenue',
      label: '总营收',
      datasetId: 'ds_orders',
      expr: 'order_amount',
      agg: 'sum',
      filterExpr: "order_status = 'completed'",
      format: '#,##0.00',
      unit: 'CNY',
      description: '已完成订单的销售总金额（不含税）',
      synonyms: ['营收', 'GMV', '销售额'],
      certified: true,
    },
    {
      id: 'm_orders',
      name: 'order_count',
      label: '订单数',
      datasetId: 'ds_orders',
      expr: 'order_id',
      agg: 'count_distinct',
      filterExpr: '',
      format: '#,##0',
      unit: '单',
      description: '去重后的订单总数',
      synonyms: ['单量'],
      certified: false,
    },
  ],
  relationships: [
    {
      id: 'rel_orders_customers',
      name: 'orders_to_customers',
      fromDatasetId: 'ds_orders',
      fromColumn: 'customer_id',
      toDatasetId: 'ds_customers',
      toColumn: 'customer_id',
      type: 'many_to_one',
      joinType: 'left_outer',
    },
  ],
  filters: [
    {
      id: 'f_completed',
      name: 'completed_orders',
      label: '已完成订单',
      datasetId: 'ds_orders',
      expr: "order_status = 'completed'",
      description: '仅统计状态为已完成的订单',
      synonyms: ['成交订单'],
    },
    {
      id: 'f_this_year',
      name: 'current_year',
      label: '本年度',
      datasetId: 'ds_orders',
      expr: "order_created_at >= date_trunc('year', current_date)",
      description: '自然年年初至今',
      synonyms: ['今年', 'YTD'],
    },
  ],
  verifiedQueries: [
    {
      id: 'vq_region_revenue',
      name: 'revenue_by_region',
      question: '今年各销售大区的营收分别是多少？',
      sql: "SELECT sales_region, SUM(order_amount) AS total_revenue\nFROM analytics.dwd.fact_orders\nWHERE order_status = 'completed'\n  AND order_created_at >= date_trunc('year', current_date)\nGROUP BY sales_region\nORDER BY total_revenue DESC",
      verifiedBy: 'data-platform@example.com',
      verifiedAt: '2026-06-15',
      useAsOnboarding: true,
    },
  ],
  glossary: [
    {
      id: 'g_gmv',
      term: 'GMV',
      definition: '商品交易总额，此处口径等同于 total_revenue（已完成订单不含税金额）',
      synonyms: ['交易额'],
    },
    {
      id: 'g_ka',
      term: 'KA',
      definition: 'Key Account，指年采购额 100 万以上的大客户',
      synonyms: ['大客户', '关键客户'],
    },
  ],
  customInstructions:
    '金额类指标默认以人民币（CNY）展示，保留两位小数。当用户未指定时间范围时，默认统计本年度（YTD）。涉及客户明细数据时提示用户该数据为机密级。',
}
