import type { OsiModel } from './osi-types'

export const defaultModel: OsiModel = {
  info: {
    name: 'sales_semantic_model',
    version: '1.0.0',
    description: '销售域语义模型：统一定义订单、客户相关的维度与指标口径',
    owner: 'data-platform@example.com',
    domain: 'sales',
    certified: true,
    tags: ['sales', 'core', 'certified'],
  },
  datasets: [
    {
      id: 'ds_orders',
      name: 'orders',
      description: '订单事实表',
      database: 'analytics',
      schema: 'dwd',
      table: 'fact_orders',
      dimensions: [
        {
          id: 'dim_order_id',
          name: 'order_id',
          expr: 'order_id',
          dataType: 'string',
          description: '订单唯一标识',
          synonyms: ['订单号'],
          isTimeDimension: false,
          isPrimaryKey: true,
        },
        {
          id: 'dim_order_date',
          name: 'order_date',
          expr: 'order_created_at',
          dataType: 'timestamp',
          description: '订单创建时间',
          synonyms: ['下单时间', '成交日期'],
          isTimeDimension: true,
          granularity: 'day',
          isPrimaryKey: false,
        },
        {
          id: 'dim_region',
          name: 'region',
          expr: 'sales_region',
          dataType: 'string',
          description: '销售大区',
          synonyms: ['大区', '区域'],
          isTimeDimension: false,
          isPrimaryKey: false,
        },
      ],
    },
    {
      id: 'ds_customers',
      name: 'customers',
      description: '客户维度表',
      database: 'analytics',
      schema: 'dim',
      table: 'dim_customers',
      dimensions: [
        {
          id: 'dim_customer_id',
          name: 'customer_id',
          expr: 'customer_id',
          dataType: 'string',
          description: '客户唯一标识',
          synonyms: ['客户ID'],
          isTimeDimension: false,
          isPrimaryKey: true,
        },
        {
          id: 'dim_segment',
          name: 'segment',
          expr: 'customer_segment',
          dataType: 'string',
          description: '客户分层',
          synonyms: ['客群', '分层'],
          isTimeDimension: false,
          isPrimaryKey: false,
        },
      ],
    },
  ],
  metrics: [
    {
      id: 'm_revenue',
      name: 'total_revenue',
      label: '总营收',
      datasetId: 'ds_orders',
      expr: 'order_amount',
      agg: 'sum',
      format: '#,##0.00',
      description: '已完成订单的销售总金额（不含税）',
      synonyms: ['营收', 'GMV', '销售额'],
    },
    {
      id: 'm_orders',
      name: 'order_count',
      label: '订单数',
      datasetId: 'ds_orders',
      expr: 'order_id',
      agg: 'count_distinct',
      format: '#,##0',
      description: '去重后的订单总数',
      synonyms: ['单量'],
    },
  ],
  relationships: [
    {
      id: 'rel_orders_customers',
      name: 'orders_to_customers',
      fromDatasetId: 'ds_orders',
      fromColumn: 'customer_id',
      toDatasetId: 'ds_customers',
      toColumn: 'customer_id',
      type: 'many_to_one',
    },
  ],
}
