import type { OsiModel } from './osi-types'

/** 将模型转换为符合 OSI 结构的普通对象 */
export function toOsiSpec(model: OsiModel) {
  const datasetName = (id: string) =>
    model.datasets.find((d) => d.id === id)?.name ?? id

  return {
    osi_version: '0.1',
    semantic_model: {
      name: model.info.name || 'untitled_model',
      version: model.info.version || '1.0.0',
      description: model.info.description || undefined,
      owner: model.info.owner || undefined,
      domain: model.info.domain || undefined,
      certified: model.info.certified,
      tags: model.info.tags.length > 0 ? model.info.tags : undefined,
    },
    datasets: model.datasets.map((ds) => ({
      name: ds.name || 'untitled_dataset',
      description: ds.description || undefined,
      source: {
        database: ds.database || undefined,
        schema: ds.schema || undefined,
        table: ds.table || undefined,
      },
      primary_key:
        ds.dimensions.filter((d) => d.isPrimaryKey).map((d) => d.name) ||
        undefined,
      dimensions: ds.dimensions
        .filter((d) => !d.isTimeDimension)
        .map((d) => ({
          name: d.name,
          expr: d.expr || d.name,
          data_type: d.dataType,
          description: d.description || undefined,
          synonyms: d.synonyms.length > 0 ? d.synonyms : undefined,
        })),
      time_dimensions: ds.dimensions
        .filter((d) => d.isTimeDimension)
        .map((d) => ({
          name: d.name,
          expr: d.expr || d.name,
          data_type: d.dataType,
          granularity: d.granularity ?? 'day',
          description: d.description || undefined,
          synonyms: d.synonyms.length > 0 ? d.synonyms : undefined,
        })),
    })),
    metrics: model.metrics.map((m) => ({
      name: m.name || 'untitled_metric',
      label: m.label || undefined,
      dataset: datasetName(m.datasetId),
      expr: m.expr || undefined,
      aggregation: m.agg,
      format: m.format || undefined,
      description: m.description || undefined,
      synonyms: m.synonyms.length > 0 ? m.synonyms : undefined,
    })),
    relationships: model.relationships.map((r) => ({
      name: r.name || 'untitled_relationship',
      type: r.type,
      from: { dataset: datasetName(r.fromDatasetId), column: r.fromColumn },
      to: { dataset: datasetName(r.toDatasetId), column: r.toColumn },
    })),
  }
}

function clean(value: unknown): unknown {
  if (Array.isArray(value)) {
    const arr = value.map(clean).filter((v) => v !== undefined)
    return arr
  }
  if (value !== null && typeof value === 'object') {
    const out: Record<string, unknown> = {}
    for (const [k, v] of Object.entries(value as Record<string, unknown>)) {
      const c = clean(v)
      if (c !== undefined) out[k] = c
    }
    return out
  }
  return value === undefined ? undefined : value
}

export function toJson(model: OsiModel): string {
  return JSON.stringify(clean(toOsiSpec(model)), null, 2)
}

const NEEDS_QUOTE = /[:#{}[\],&*?|<>=!%@`"']|^\s|\s$|^$/

function yamlScalar(value: unknown): string {
  if (value === null || value === undefined) return 'null'
  if (typeof value === 'boolean' || typeof value === 'number')
    return String(value)
  const s = String(value)
  if (NEEDS_QUOTE.test(s) || /^(true|false|null|yes|no|~)$/i.test(s)) {
    return JSON.stringify(s)
  }
  return s
}

function yamlify(value: unknown, indent: number): string {
  const pad = '  '.repeat(indent)
  if (Array.isArray(value)) {
    if (value.length === 0) return `${pad}[]`
    return value
      .map((item) => {
        if (item !== null && typeof item === 'object') {
          const inner = yamlify(item, indent + 1)
          // 将第一行合并到 "- " 后
          const lines = inner.split('\n')
          const first = lines[0].trimStart()
          const rest = lines.slice(1)
          return [`${pad}- ${first}`, ...rest].join('\n')
        }
        return `${pad}- ${yamlScalar(item)}`
      })
      .join('\n')
  }
  if (value !== null && typeof value === 'object') {
    const entries = Object.entries(value as Record<string, unknown>)
    if (entries.length === 0) return `${pad}{}`
    return entries
      .map(([k, v]) => {
        if (v !== null && typeof v === 'object') {
          if (Array.isArray(v) && v.length === 0) return `${pad}${k}: []`
          return `${pad}${k}:\n${yamlify(v, indent + 1)}`
        }
        return `${pad}${k}: ${yamlScalar(v)}`
      })
      .join('\n')
  }
  return `${pad}${yamlScalar(value)}`
}

export function toYaml(model: OsiModel): string {
  const spec = clean(toOsiSpec(model))
  return `# Open Semantic Interchange (OSI) Specification\n# Generated by OSI Configurator\n${yamlify(spec, 0)}\n`
}
